# Instagram Video İndirme + Analiz + Sil
# Kur: pip install yt-dlp

mkdir temp_videos

# === REELS (28 adet) ===
yt-dlp --cookies-from-browser chrome -o "temp_videos/alex2learn_DWoxW7pjjkH.%%(ext)s" "https://www.instagram.com/reel/DWoxW7pjjkH/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/conec.ai_DW1TlXCgqXM.%%(ext)s" "https://www.instagram.com/reel/DW1TlXCgqXM/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/ferdi.sahiin_DW50aByAVQJ.%%(ext)s" "https://www.instagram.com/reel/DW50aByAVQJ/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/julian.goldie__DV7_F3tk3ye.%%(ext)s" "https://www.instagram.com/reel/DV7_F3tk3ye/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/iha089_DW2Iu8RSMti.%%(ext)s" "https://www.instagram.com/reel/DW2Iu8RSMti/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/berkayylcn.ai_DW1DUOcDETe.%%(ext)s" "https://www.instagram.com/reel/DW1DUOcDETe/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/allyoucanchi_DWr5eh4iYOg.%%(ext)s" "https://www.instagram.com/reel/DWr5eh4iYOg/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/noevarner.ai_DW4gVuCDYTM.%%(ext)s" "https://www.instagram.com/reel/DW4gVuCDYTM/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/githubsignals_DW71Tn0DL06.%%(ext)s" "https://www.instagram.com/reel/DW71Tn0DL06/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/githubsignals_DW-_6D0DGmD.%%(ext)s" "https://www.instagram.com/reel/DW-_6D0DGmD/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/geodza_DXAcJmtk6Uu.%%(ext)s" "https://www.instagram.com/reel/DXAcJmtk6Uu/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/github.awesome_DXDRegnk_As.%%(ext)s" "https://www.instagram.com/reel/DXDRegnk_As/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/githubsignals_DW9QN3MDIWE.%%(ext)s" "https://www.instagram.com/reel/DW9QN3MDIWE/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/marc.kaz_DW34yHrjkcf.%%(ext)s" "https://www.instagram.com/reel/DW34yHrjkcf/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/maxjohnscn_DW3VHuzjGS9.%%(ext)s" "https://www.instagram.com/reel/DW3VHuzjGS9/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/dijitalmasallar_DXCPqHsD1Jn.%%(ext)s" "https://www.instagram.com/reel/DXCPqHsD1Jn/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/synthixlabs_DWunOJSkwyJ.%%(ext)s" "https://www.instagram.com/reel/DWunOJSkwyJ/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/cihanerden33_DWfvF5-MU75.%%(ext)s" "https://www.instagram.com/reel/DWfvF5-MU75/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/itssuleymanacir_DSFTtj-DNcC.%%(ext)s" "https://www.instagram.com/reel/DSFTtj-DNcC/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/yoeldelrio___DXCmvifDqWX.%%(ext)s" "https://www.instagram.com/reel/DXCmvifDqWX/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/cicekileteknoloji_DW4e0KxDpM0.%%(ext)s" "https://www.instagram.com/reel/DW4e0KxDpM0/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/marc.kaz_DW36E-cDpIW.%%(ext)s" "https://www.instagram.com/reel/DW36E-cDpIW/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/mr.pynk_DWpU8KpI_e6.%%(ext)s" "https://www.instagram.com/reel/DWpU8KpI_e6/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/codingknowledge_DWT_jhiEo7W.%%(ext)s" "https://www.instagram.com/reel/DWT_jhiEo7W/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/_eduard.d____DV_xiadjiYc.%%(ext)s" "https://www.instagram.com/reel/DV_xiadjiYc/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/nicholas.puru_DVonHgkgIXc.%%(ext)s" "https://www.instagram.com/reel/DVonHgkgIXc/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/ohmo.ai_DV9gtHDkl5L.%%(ext)s" "https://www.instagram.com/reel/DV9gtHDkl5L/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/ohmo.ai_DWXKi88k7hk.%%(ext)s" "https://www.instagram.com/reel/DWXKi88k7hk/"

# === POSTS (video olanlar) ===
yt-dlp --cookies-from-browser chrome -o "temp_videos/thevibefounder_DWz1KxNjo75.%%(ext)s" "https://www.instagram.com/p/DWz1KxNjo75/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/hacklearn___DV089QmEoZf.%%(ext)s" "https://www.instagram.com/p/DV089QmEoZf/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/axon.neuro.ai_DWXzFt3EjhI.%%(ext)s" "https://www.instagram.com/p/DWXzFt3EjhI/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/r10net_DWD2oGnimkj.%%(ext)s" "https://www.instagram.com/p/DWD2oGnimkj/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/f16.roo_DWtiTwtjLiu.%%(ext)s" "https://www.instagram.com/p/DWtiTwtjLiu/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/charlieautomates_DWuY1PymJfZ.%%(ext)s" "https://www.instagram.com/p/DWuY1PymJfZ/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/isanurdogdu_DXBwmqpiKQV.%%(ext)s" "https://www.instagram.com/p/DXBwmqpiKQV/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/parasmadan.in_DW7IzJyE8r1.%%(ext)s" "https://www.instagram.com/p/DW7IzJyE8r1/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/brunobracaioli_DW81hGsjlD3.%%(ext)s" "https://www.instagram.com/p/DW81hGsjlD3/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/speedy_devv_DXAXbiYjPre.%%(ext)s" "https://www.instagram.com/p/DXAXbiYjPre/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/anastasis_king_DWYY6k-DMxU.%%(ext)s" "https://www.instagram.com/p/DWYY6k-DMxU/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/myself_immortal_DWF_80qj-3l.%%(ext)s" "https://www.instagram.com/p/DWF_80qj-3l/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/tenfoldmarc_DXAzOJojLrR.%%(ext)s" "https://www.instagram.com/p/DXAzOJojLrR/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/codingknowledge_DWeBJC4kqX4.%%(ext)s" "https://www.instagram.com/p/DWeBJC4kqX4/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/githubprojects_DVWCcubj6Ua.%%(ext)s" "https://www.instagram.com/p/DVWCcubj6Ua/"
yt-dlp --cookies-from-browser chrome -o "temp_videos/mobileappdaily__DV8UCr0im1y.%%(ext)s" "https://www.instagram.com/p/DV8UCr0im1y/"